### ISSUE TITLE
Activation of the addon fails c_utils not found

### ISSUE THREAD

**Issue by diramazioni** [3DSinghVFX/an_extra_nodes#2]
Hello, I'd love to try out extra nodes but upon activation, after the installation in 2.9.4, Auto_load.py fails because it can't find c_utils, 
I suspect because of a different python version 2.9.4 ships with python 3.9 but c_utils seems to be compiled for 3.8.

My question is: how to compile it for current python? Can you write some instructions in the README?

**Comment by 3DSinghVFX** [comment]
@diramazioni Hi.
Yes, I have not updated. However, you can download the full AN+EN addon from https://github.com/3DSinghVFX/animation_nodes/releases
